# Generated by Django 5.0.1 on 2026-02-11 21:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_nights', models.IntegerField(default=1)),
                ('max_nights', models.IntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('linked_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='properties.property')),
            ],
            options={
                'verbose_name_plural': 'availabilities',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('guests_count', models.IntegerField(default=1)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('service_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('paid', 'Payée'), ('cancelled', 'Annulée'), ('completed', 'Terminée'), ('refunded', 'Remboursée')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Message au propriétaire', max_length=500)),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=255)),
                ('stripe_session_id', models.CharField(blank=True, max_length=255)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_as_guest', to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_as_host', to=settings.AUTH_USER_MODEL)),
                ('linked_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='properties.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('linked_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_dates', to='properties.property')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('linked_property', 'date')},
            },
        ),
    ]
